all:

	@cd ./util>/dev/null;	make
	@cd ./errlog>/dev/null;	make
	@cd ./sec>/dev/null;	make
	@cd ./hsmcmd>/dev/null;	make
	@cd ./comm>/dev/null;	make
	@cd ./ssm>/dev/null;	make
	@cd ./kmc>/dev/null;	make
clean:
	@cd ./util>/dev/null;	make clean
	@cd ./errlog>/dev/null;	make clean
	@cd ./sec>/dev/null;	make clean
	@cd ./hsmcmd>/dev/null;	make clean
	@cd ./comm>/dev/null;	make clean
	@cd ./ssm>/dev/null;	make clean
	@cd ./kmc>/dev/null;	make clean
	

